name: Publish hcss shinyapp docker image

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push hcss shinyapp docker images to deployment server
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push hcss shinyapp docker
        uses: docker/build-push-action@v5
        with:
          push: true
          target: hcss-shinyapp-deploy
          tags: |
            ghcr.io/hcss-data-lab/shinyapp/hcss_shinyapp:latest
